CREATE TABLE EMPLOYEES(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
JOIN_DATE DATE
);

INSERT INTO employees (emp_name, department, join_date) VALUES
('Arun Kumar', 'IT', '2024-01-10'),
('Vijay Raj', 'HR', '2024-02-15'),
('Sneha Priya', 'Finance', '2024-01-25'),
('Karthik S', 'IT', '2024-03-05'),
('Divya R', 'Marketing', '2024-02-01');

SELECT * FROM EMPLOYEES

-- EMPLOYEES ATTENDANCE MANAGEMENT SYESEM:

STEP 1
CREATE DATABASE ATTENDANCE_SYSTEM

STEP 2
USE ATTENDANCE_SYSTEM

 DESCRIBE EMPLOYEES;
 DESCRIBE LEAVE_REQUEST;
 describe ATTENDANCE;	

STEP 3 CREATE EMPLOYEES TABLE:
CREATE TABLE EMPLOYEES(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
JOIN_DATE DATE
);

STEP 4 CREATE ATTENDANCE TABLE:
CREATE TABLE ATTENDANCE(
ATTENDANCE_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_ID INT,
ATTENDANCE_DATE DATE,
STATUS VARCHAR(10),
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

STEP 5 CREATE LEAVE_REQUEST TABLE;
CREATE TABLE LEAVE_REQUEST(
LEAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_ID INT,
LEAVE_DATE DATE,
REASON VARCHAR(100),
STATUS VARCHAR(20),
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

STEP 6 INSERT THE VALUES OF EMPLOYEES , ATTENDANCE AND LEAVD_REQUEST:

-- INSERT EMPLOYEES --
INSERT INTO employees (emp_name, department, join_date) VALUES
('Arun Kumar', 'IT', '2024-01-10'),
('Vijay Raj', 'HR', '2024-02-15'),
('Sneha Priya', 'Finance', '2024-01-25'),
('Karthik S', 'IT', '2024-03-05'),
('Divya R', 'Marketing', '2024-02-01');

-- INSERT ATTENDANCE --
INSERT INTO attendance (emp_id, attendance_date, status) VALUES
-- Arun
(1,'2024-03-01','Present'),
(1,'2024-03-02','Present'),
(1,'2024-03-03','Absent'),

-- Vijay
(2,'2024-03-01','Present'),
(2,'2024-03-02','Absent'),
(2,'2024-03-03','Present'),

-- Sneha
(3,'2024-03-01','Present'),
(3,'2024-03-02','Present'),
(3,'2024-03-03','Present'),

-- Karthik
(4,'2024-03-01','Absent'),
(4,'2024-03-02','Present'),

-- Divya
(5,'2024-03-01','Present'),
(5,'2024-03-02','Present');

-- INSERT LEAVE_REQUEST --
INSERT INTO leave_request (emp_id, leave_date, reason, status) VALUES
(1, '2024-03-05', 'Sick Leave', 'Approved'),
(2, '2024-03-06', 'Personal Work', 'Pending'),
(3, '2024-03-07', 'Family Function', 'Approved'),
(4, '2024-03-08', 'Medical Appointment', 'Rejected'),
(5, '2024-03-09', 'Travel', 'Pending');

-- ATTENDANCE PERCENTAGE --
SELECT EMP_ID,
COUNT(CASE WHEN STATUS='PRESENT' THEN 1 END)* 100.0 /COUNT(*) AS ATTENDACNE_PERCENTAGE FROM ATTENDANCE GROUP BY EMP_ID;

-- JOINS --
 SELECT EMPLOYEES.EMP_ID,ATTENDANCE.ATTENDANCE_DATE,ATTENDANCE.STATUS FROM EMPLOYEES INNER JOIN ATTENDANCE ON EMPLOYEES.EMP_ID=ATTENDANCE.EMP_ID;
 SELECT EMPLOYEES.EMP_NAME,EMPLOYEES.DEPARTMENT,ATTENDANCE.STATUS FROM EMPLOYEES INNER JOIN ATTENDANCE ON EMPLOYEES.EMP_ID=ATTENDANCE.EMP_ID WHERE STATUS='ABSENT';

 
 
 
 
 
 
 